import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'; // 引入 Link 組件用來做導航

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
					<nav className="bg-gray-800 text-white p-4">
					  <ul className="flex space-x-4">
					    <li><Link href="/">首頁</Link></li>
					    <li><Link href="/login">登入</Link></li>
					  </ul>
					</nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}